/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package validacpf.Renan.Form;

import javax.swing.JOptionPane;

/**
 *
 * @author Informática
 */
public class ValidacaoCPF extends javax.swing.JFrame {

    /**
     * Creates new form ValidacaoCPF
     */
    public ValidacaoCPF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_cpf = new javax.swing.JFormattedTextField();
        bt_validar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_validar.setText("VALIDAR");
        bt_validar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_validarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_validar))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_validar)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_validarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_validarActionPerformed
        String CNPJ = txt_cpf.getText();
        int n1 = CNPJ.charAt(0) - 48;        int n2 = CNPJ.charAt(1) - 48;
        int n3 = CNPJ.charAt(2) - 48;        int n4 = CNPJ.charAt(3) - 48;
        int n5 = CNPJ.charAt(4) - 48;        int n6 = CNPJ.charAt(5) - 48;
        int n7 = CNPJ.charAt(6) - 48;        int n8 = CNPJ.charAt(7) - 48;
        int n9 = CNPJ.charAt(8) - 48;        int n10 = CNPJ.charAt(9) - 48;
        int n11 = CNPJ.charAt(10) - 48;      int n12 = CNPJ.charAt(11) - 48;
        int n13 = CNPJ.charAt(12) - 48;      int n14 = CNPJ.charAt(13) - 48;
        //Calculo aqui
        int sm = (n1*5)+(n2*4)+(n3*3)+(n4*2)+(n5*9)+(n6*8)+(n7*7)+(n8*6)+(n9*5)+(n10*4)+(n11*3)+(n12*2);
        int DV1=11 - (sm % 11);
        int sm2= (n1*6)+(n2*5)+(n3*4)+(n4*3)+(n5*2)+(n6*9)+(n7*8)+(n8*7)+(n9*6)+(n10*5)+(n11*4)+(n12*3)+(DV1*2);
        int DV2=11 - (sm2 % 11);
        if (CNPJ.equals("00000000000000") || CNPJ.equals("11111111111111") || CNPJ.equals("22222222222222")
            || CNPJ.equals("33333333333333") || CNPJ.equals("44444444444444") || CNPJ.equals("55555555555555")
            || CNPJ.equals("66666666666666") || CNPJ.equals("77777777777777") || CNPJ.equals("8888888888888")
            || CNPJ.equals("99999999999999"))
        {
            JOptionPane.showMessageDialog(null, "CNPJ INVÁLIDO!!!");
        }else{
            if((DV1==n13||DV1==10||DV1==11)&&(DV2==n14||DV2==10||DV2==11)){
                JOptionPane.showMessageDialog(null, "OK");
                
            }else{
                JOptionPane.showMessageDialog(null, "CNPJ  INVÁLIDO!!!");
            }

        }
        System.out.println("___________________");
        System.out.println(DV1+" "+DV2);
        System.out.println(n13+" "+n14);
        // System.out.print(n1);
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_validarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValidacaoCPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValidacaoCPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValidacaoCPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValidacaoCPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ValidacaoCPF().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_validar;
    private javax.swing.JFormattedTextField txt_cpf;
    // End of variables declaration//GEN-END:variables
}
